dist: xenial
sudo: false
language: csharp
dotnet: 3.1.200
mono: none
script:
  - dotnet restore ./GrobExp.Compiler.sln --verbosity m
  - dotnet build --configuration Release --framework netstandard2.0 ./GrobExp.Compiler/GrobExp.Compiler.csproj
  - dotnet build --configuration Release --framework netcoreapp3.1 ./GrobExp.Compiler.Tests/GrobExp.Compiler.Tests.csproj
  - dotnet test --no-build --configuration Release --framework netcoreapp3.1 --filter TestCategory!=LongRunning\&TestCategory!=FailingOnNetCore ./GrobExp.Compiler.Tests/GrobExp.Compiler.Tests.csproj
