dist: xenial
sudo: false
language: csharp
dotnet: 5.0.103
mono: none
script:
  - git fetch --unshallow # in order to make Nerdbank.GitVersioning.Tasks.GetBuildVersion work
  - dotnet restore ./GrobExp.Compiler.sln --verbosity m
  - dotnet build --configuration Release --framework netstandard2.0 ./GrobExp.Compiler/GrobExp.Compiler.csproj
  - dotnet build --configuration Release --framework net5.0 ./GrobExp.Compiler.Tests/GrobExp.Compiler.Tests.csproj
  - dotnet test --no-build --configuration Release --framework net5.0 --filter TestCategory!=LongRunning\&TestCategory!=FailingOnNetCore ./GrobExp.Compiler.Tests/GrobExp.Compiler.Tests.csproj
